# Generated by Django 5.0.3 on 2024-03-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarhammerCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_campagne', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image_campagne', models.ImageField(blank=True, null=True, upload_to='image_campagne/')),
                ('campagne_etat', models.CharField(choices=[('En cours', 'En cours'), ('En pause', 'En pause'), ('Terminée', 'Terminée')], max_length=20)),
                ('maitre_du_jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
            },
        ),
        migrations.CreateModel(
            name='WarhammerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('race', models.CharField(choices=[('Elfe', 'Elfe'), ('Nain', 'Nain'), ('Humain', 'Humain'), ('Halfeling', 'Halfeling')], max_length=50)),
                ('sexe', models.CharField(choices=[('Femelle', 'Femelle'), ('Mâle', 'Mâle')], max_length=50)),
                ('vocation', models.CharField(choices=[('Forestier', 'Forestier'), ('Filou', 'Filou'), ('Guerrier', 'Guerrier'), ('Erudit', 'Erudit')], max_length=50)),
                ('alignement', models.CharField(choices=[('Loyal', 'Loyal'), ('Mauvais', 'Mauvais'), ('Neutre', 'Neutre'), ('Chaotique', 'Chaotique'), ('Bon', 'Bon')], max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('taille', models.CharField(blank=True, max_length=50, null=True)),
                ('poids', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cheveux', models.CharField(blank=True, max_length=50, null=True)),
                ('yeux', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_personnage', models.ImageField(blank=True, null=True, upload_to='photo_perso/')),
                ('point_destin', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('debouches', models.TextField(blank=True, default='Ajouter débouchés', null=True)),
                ('point_folie', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('langue', models.CharField(blank=True, default='A définir', max_length=50, null=True)),
                ('note', models.TextField(blank=True, default='Aucune note', null=True)),
                ('mort_tuer', models.TextField(blank=True, default='Ajouter morts tués', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warhammer.warhammercampagne')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
